### ISSUE TITLE
Fix `finetuner` to work with 8 GPUs

### ISSUE THREAD

**Issue by wbrown** [coreweave/kubernetes-cloud#170]
Currently, the `finetuner` crashes/exits if you try to use 8 GPUs. It works if you use 7, and it does not appear to be memory-capacity related. If I had to guess, it's probably running into some shared memory issue.

It's probably DeepSpeed triggering this issue.

**Comment by rtalaricw** [comment]
@microcosem This issue has been addressed. The documentation [](https://docs.coreweave.com/coreweave-machine-learning-and-ai/how-to-guides-and-tutorials/model-training-guides/fine-tuning/finetuning-machine-learning-models) needed to be updated to say 8 GPUs instead of 7.

**Comment by microcosem** [comment]
Thanks for the visibility Rahul!
