### ISSUE TITLE
Incorrect call to patch_namespaced_custom_object

### ISSUE THREAD

**Issue by andrewww** [coreweave/kubernetes-cloud#35]
https://github.com/coreweave/kubernetes-cloud/blob/03c2991d533a698dc296a827e340ace070afe46f/virtual-server/examples/python/vsclient.py#L56

This call needs an additional argument, `name`:
```
return self.api.patch_namespaced_custom_object(
            VSClient.GROUP, VSClient.VERSION, namespace, VSClient.PLURAL, name,manifest)
```

**Comment by goock** [comment]
Hey @andrewww, you are absolutely right. Thank you for reporting this.
I will prepare PR with the fix, and I'll add an example with a manifest update.
